// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/BNPrashanth/poc-go-helm/models"
)

// DefaultOKCode is the HTTP code returned for type DefaultOK
const DefaultOKCode int = 200

/*DefaultOK OK

swagger:response defaultOK
*/
type DefaultOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewDefaultOK creates DefaultOK with default headers values
func NewDefaultOK() *DefaultOK {

	return &DefaultOK{}
}

// WithPayload adds the payload to the default o k response
func (o *DefaultOK) WithPayload(payload *models.GeneralResponse) *DefaultOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the default o k response
func (o *DefaultOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DefaultOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
