// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Poc Helm
Test API fo poc-helm


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: Test API fo poc-helm

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
