swagger: '2.0'
info:
  title: Poc Helm
  description: Test API fo poc-helm
  contact:
    name: Test API fo poc-helm
  version: 1.0.0
schemes: [
  "http"
]
consumes: [
  "application/json"
]
produces: [
  "application/json"
]
paths:
  /:
    $ref: ./default.yml