apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poc-helm
  name: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - image: bnprashanth/poc-helm
        name: poc-helm
        resources: {}
        env:
        - name: {{ printf "%s_TEST_CONFIG" .Values.service.name | upper | replace "-" "_" }}
          valueFrom:
            configMapKeyRef:
              name: poc-helm-config
              key: test
        - name: {{ printf "%s_CONFIG_PATH" .Values.service.name | upper | replace "-" "_" }}
          value: /etc/{{ .Values.service.name | replace "-" "_" }}/default.json
        volumeMounts:
        - name: poc-helm-config
          mountPath: /etc/{{ .Values.service.name | replace "-" "_" }}/
      volumes:
      - name: poc-helm-config
        configMap:
          name: poc-helm-config
status: {}