apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poc-helm
  name: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - image: bnprashanth/poc-helm
        name: poc-helm
        resources: {}
        env:
        - name: {{ printf "%s_TEST_CONFIG" .Values.service.name | upper | replace "-" "_" }}
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.service.name }}-config
              key: test
status: {}