apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poc-helm
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodeport }}
  selector:
    app: poc-helm
status:
  loadBalancer: {}